#!/bin/bash

# This Script aims to create image pull secret in apps repo 

REGION=eu-west-1

TOKEN=`aws ecr --region=$REGION get-authorization-token --output text --query authorizationData[].authorizationToken | base64 -d | cut -d: -f2`

kubectl delete secret --ignore-not-found build-ecr -n ${NAMESPACE}

kubectl create secret docker-registry build-ecr \
 --docker-server=https://732440210582.dkr.ecr.${REGION}.amazonaws.com \
 --docker-username=AWS \
 --docker-password="${TOKEN}" \
 -n ${NAMESPACE}
